### ISSUE TITLE
ImportError: cannot import name 'MutableMapping' from 'collections'

### ISSUE THREAD

**Issue by dentalfloss1** [transientskp/pyse#44]
Shows up on pip install. My python version is 3.10. 
Solution appears to be: 
https://stackoverflow.com/questions/70870041/cannot-import-name-mutablemapping-from-collections

**Comment by dentalfloss1** [comment]
This only shows up in the pip install. Works with git install.

**Comment by HannoSpreeuw** [comment]
By `pip install` do you mean `pip install radio-pyse`?

**Comment by dentalfloss1** [comment]
Yes
Sent from my iPhone

On Jan 23, 2024, at 5:06 AM, Hanno Spreeuw ***@***.***> wrote:

﻿
  [EXTERNAL]

By pip install do you mean pip install radio-pyse?

**Comment by suvayu** [comment]
A new version is available on PyPI after over 6 yrs!

https://pypi.org/project/radio-pyse/

Please test and open a new issue if there are any problems.
