### ISSUE TITLE
Missing argument in `ImageData.reverse_se`

### ISSUE THREAD

**Issue by suvayu** [transientskp/pyse#51]
### Description

Mypy tells me:
```
sourcefinder/image.py:468: error: Missing positional argument "anl" in call to "extract"  [call-arg]
```

I don't know what should be the correct value of `anl` here, so I
couldn't fix it.

### Remarks

This method is not used anywhere in PySE.  I'm guessing this was
implemented because it might be useful elsewhere in TraP?  If so,
there should be explicit tests for the `ImageData` class testing all
potential downstream API calls.  There are no such tests.

**Comment by HannoSpreeuw** [comment]
Nice catch, there is a typo. It should be 

```
 def reverse_se(self, det, anl):
 ...
    results = self.extract(det=det, anl=det)
```

`ImageData.extract`  is a fundamental method of PySE and does appear in the unit tests, e.g. [here](https://github.com/transientskp/pyse/blob/91f8c116a59da2769eb78e379bc90a627b70bef4/test/test_source_measurements.py#L56). Perhaps there is no call to this method outside the tests because other methods do not depend on it. That is because it is a top level method.
But perhaps you mean that `ImageData.reverse_se` is not used nor tested anywhere in PySE?  Let me check that.

**Comment by suvayu** [comment]
Okk, I'll fix the typo.

Regarding tests, I meant both. The example you cite doesn't count, because it's not actually testing the API, it's part of the setup for another test. If we were to refactor `ImageData.extract`, that indirect use wouldn't help. We would see unrelated failures, which we would have to debug to realise it's an indirect effect of the refactor.

**Comment by jdswinbank** [comment]
Hey @HannoSpreeuw — I'm not sure that `anl=det` is right.

This seems to date back to April 2014, when somebody (*cough*) removed a default `None` as the value of `anl` in `ImageData.extract` (see [here](https://github.com/transientskp/tkp/commit/0e87772b388c0f69bc261138072f0a701b2d29be#diff-592f3653d33db7ef6aa3197f30390c906bee0cbb48f3e2e4086d6fe286921cd7L355)). That implies that the call in `reverse_se` should be:

```python
    ...
    results = self.extract(det=det, anl=None)
    ....
```

(Untested, though).

That said, I'm pretty sure that `reverse_se` itself dates back into the mists of time and has probably never been used in anger. I'd guess it needs a bunch of thinking before putting it into practice.

**Comment by suvayu** [comment]
Thanks John, I'll hold off on the fix.

**Comment by HannoSpreeuw** [comment]
Indeed, `reverse_se` is not tested. I could write a unit test or we could remove it. 

What is the use case?
It could be that the `reverse_se` method is to applied not on Stokes I, but e.g. on Stokes V images, with a circularly polarized source. The peak spectral brightness at the position of the source is negative and high enough to be identified as a cosmic source.
You can then extract this source using `reverse_se`.

But there is the comment: 
```
        Obviously, there should be no sources in the negative image, so this
        tells you about the false positive rate.
```
So perhaps `reverse_se` should be applied on the "negation" of a Stokes I image - which positive pixel values should always be noise related - to determine what an appropriate threshold for source detection in the original Stokes I image should be.

**Comment by jdswinbank** [comment]
Hi Hanno — it's been a long time, but I think your second use case (determining noise based on a negation of the Stokes I image) sounds like the original idea.

**Comment by HannoSpreeuw** [comment]
Allright. We will keep it and I will fix it and include a unit test, that should not be so hard.

**Comment by HannoSpreeuw** [comment]
`anl=None` will not work because of [line 419  `if anl > det`](https://github.com/transientskp/pyse/blob/f81db77b528b1e2bf05d18988be2887a166b5747/sourcefinder/image.py#L419), it yields:
```
TypeError: '>' not supported between instances of 'NoneType' and 'float'
```
but I'll think of something else.
