### ISSUE TITLE
Missing FitsImage fixes

### ISSUE THREAD

**Issue by tmillenaar** [transientskp/pyse#62]
Hey guys,

I was trying to read fits images using the pyse accessors, but ran into an error while the fits accessor from tkp worked fine. I looked into it and found that the version in pyse is from 7 years ago and is missing some fixes.

The problem I ran into is that I encounter the following line:
https://github.com/transientskp/pyse/blob/43124dc7463f3b841d744119e630fd5fcc42ba30/sourcefinder/accessors/fitsimage.py#L125
but don't have 'RESTFRQ' in the header, hence a KeyError is raised.

It looks like this was addressed in the following tkp commit:
https://github.com/transientskp/tkp/commit/ae5aa598b142567138058771488c87dc9b6acfeb

I imagine the simplest way to address this is by cargo-culting `fits_image.py` from tkp:
https://github.com/transientskp/tkp/blob/8a19cd23c7141c66c1ee8e42295957bbcf809531/tkp/accessors/fitsimage.py 

@suvayu Shall I make a PR with the copied fits_image.py or would you prefer to tackle this yourself?

Cheers,
Timo

**Comment by suvayu** [comment]
Hey Timo,

Interesting find. Please feel free to open a PR. I'm now wondering if there
are other similar backports necessary. If so, how can we find them?
-- 
Suvayu

Open source is the future. It sets us free.

**Comment by tmillenaar** [comment]
I'll manually check the other accessors as well

**Comment by tmillenaar** [comment]
I went through the diffs of the files. It looks like most differences were related to
 - IOError vs OSError
 - logger.warn vs logger.warning
 - six metaclass vs buildin metaclass
 - formatting

I tried to stay away form the formatting changes, i.e. leave it as much as-is in pyse at the moment.

MR: https://github.com/transientskp/pyse/pull/63

**Comment by suvayu** [comment]
Thanks,the implementation of these data accessors are a bit over-engineered, e.g. the use of metaclasses.  It should be simplified (see: #53).
