### ISSUE TITLE
Cannot import sourcefinder module on master

### ISSUE THREAD

**Issue by tmillenaar** [transientskp/pyse#73]
Hey all, low priority remark here ^^

When I check out the master branch I cannot import the sourcefinder module because `sourcefinder/__init__.py `contains the following line: `from ._version import __version__`, but _version does not exist. @suvayu could it simply be that this file was never added to the git repo? 

Cheers,
Timo

**Comment by HannoSpreeuw** [comment]
@tmillenaar Is this still a problem or do you consider it solved?

**Comment by tmillenaar** [comment]
Ah apologies for the scilence on this matter.
Yes thanks, I consider this done. Feel free to close the issue.
