### ISSUE TITLE
Release from master branch

### ISSUE THREAD

**Issue by tmillenaar** [transientskp/pyse#76]
Hey all,

I've been using the pyse master branch for a while. I can't use the latest pip install (0.3.1) because master contains some relevant fixes (most notably fixes in the fits accessor). @suvayu are you okay with releasing the current master as v0.3.2? Then I can again pip install the package.

Cheers,
Timo

**Comment by suvayu** [comment]
Sure, I'll see if I can release before the weekend, otherwise early next week.

**Comment by tmillenaar** [comment]
Great, thanks :)

**Comment by suvayu** [comment]
Released [0.3.2](https://pypi.org/project/radio-pyse/0.3.2/).
